/**********************************************************************
 * Extern for AmazonCognitoIdentity
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var AmazonCognitoIdentity = {
  "AuthenticationDetails": function () {},
  "AuthenticationHelper": function () {},
  "CognitoAccessToken": function () {},
  "CognitoIdToken": function () {},
  "CognitoRefreshToken": function () {},
  "CognitoUser": function () {},
  "CognitoUserAttribute": function () {},
  "CognitoUserPool": function () {},
  "CognitoUserSession": function () {},
  "DateHelper": function () {}
};
/**********************************************************************
 * End Generated Extern for AmazonCognitoIdentity
/**********************************************************************/
